version: '3'

volumes:
  full_stack_app_local_postgres_data: {}
  full_stack_app_local_postgres_data_backups: {}



services:
  django: &django
    restart: always
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: full_stack_app_local_django
    container_name: full_stack_app_local_django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    restart: always
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: full_stack_app_production_postgres
    container_name: full_stack_app_local_postgres
    volumes:
      - full_stack_app_local_postgres_data:/var/lib/postgresql/data
      - full_stack_app_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  docs:
    image: full_stack_app_local_docs
    container_name: full_stack_app_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./full_stack_app:/app/full_stack_app:z
    ports:
      - '9000:9000'
    command: /start-docs

  redis:
    image: redis:6
    restart: always
    container_name: full_stack_app_local_redis

  celeryworker:
    <<: *django
    image: full_stack_app_local_celeryworker
    container_name: full_stack_app_local_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker
    restart: always

  celerybeat:
    <<: *django
    image: full_stack_app_local_celerybeat
    container_name: full_stack_app_local_celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    restart: always
    command: /start-celerybeat

  flower:
    <<: *django
    image: full_stack_app_local_flower
    container_name: full_stack_app_local_flower
    ports:
      - '5555:5555'
    command: /start-flower
    restart: always
