# Generated by Django 4.2.7 on 2023-11-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
                ("completed", models.BooleanField(default=False)),
                ("deleted", models.BooleanField(default=False)),
                ("dueDate", models.DateTimeField()),
                ("startDate", models.DateTimeField()),
            ],
        ),
    ]
